### ISSUE TITLE
有料プラン

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#142]
OpenAI API使用しているため、たくさん使いたい人向け

**Comment by R1013-T** [comment]
できれば全部無料でやりたいんだけど〜

**Comment by naruse666** [comment]
limitを超えたら利用できなくなるのはやめたい。
やっぱ従量課金??

ユーザーはアプリ開発者なのでlimit到達で処理をやめるとユーザーのアプリケーションはエラーを返しまくることになる。

**Comment by R1013-T** [comment]
そうですね、
[従量課金](https://docs.stripe.com/billing/subscriptions/usage-based?locale=ja-JP)か[サブスク](https://docs.stripe.com/subscriptions)ですね。

今のところ有料プランの実装は優先度低めで考えています。

**Comment by naruse666** [comment]
優先度は確かに低めでいいですね！

**Comment by R1013-T** [comment]
https://github.com/TECH-C-LT/Peace-Net/issues/new
