### ISSUE TITLE
ドキュメント作成

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#17]

**Comment by waya279** [comment]
ちなみにドキュメントってどういうのですか？
サイト関連とかですか？
それとも、今後の話し合いまとめとか発表資料とかですか？

**Comment by R1013-T** [comment]
@waya279 
ドキュメントサイトの作成です！
APIの取扱説明書
https://www.notion.so/ryu1013-share/54a18119076c4fd1aa5180baf865f97b?pvs=4#f190779dc4ae4f0ead1484a15bcc085b
