### ISSUE TITLE
ISSUE_TEMPLATEを追加

### ISSUE THREAD

**Issue by naruse666** [TECH-C-LT/Peace-Net#182]
二種類あればいいかな。
- Bug fix
- Feature

### 参考
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

syntax: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by R1013-T** [comment]
webにもお問合せとしてリンクを追加する
