### ISSUE TITLE
Honoのカスタムロガーを実装する

### ISSUE THREAD

**Issue by naruse666** [TECH-C-LT/Peace-Net#196]
適当に考えたフォーマット
`timestamp: (api-version|commit) "path" [Log level]: ...log`
https://hono.dev/docs/middleware/builtin/logger#options

pathは組み込みのロガーに入ってるか。

リクエストボディーも出すとguardianでどんなものが検知されたか見れる

**Comment by R1013-T** [comment]
`console.log`が何が違うのかわかっていない

**Comment by naruse666** [comment]
みた感じ単なる`console.log`のラッパーで決められたフォーマットで出すことでデバッグしやすくなることを期待してます！
例えばproduction環境で未知のエラー出た時に重宝します ✨

**Comment by naruse666** [comment]
#197 でworkersのログを出している
そのドキュメントにもカスタムロガーの記載があるから、Honoとworkersのドキュメントの違いを見たい
https://developers.cloudflare.com/workers/observability/logs/workers-logs/#add-custom-logs
