### ISSUE TITLE
チーム名

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#2]
チーム名を決めて、スプレッドシートに記入しましょう！

https://docs.google.com/spreadsheets/d/18hZzYSmJJJ_JrZlVAp5V4cL_0poQ71mlwSrg8fTHOE8/edit?gid=2029924881#gid=2029924881

- [x] スプレッドシートへ記入

**Comment by naruse666** [comment]
- TECH.C. 東福
- でも平和ならOKです

**Comment by waya279** [comment]
「でも平和ならOKです」も面白いですね笑
発表の際に、いい感じに盛り込めそうですね笑

**Comment by R1013-T** [comment]
@waya279 
ちなみに発表はお願いします🙇

**Comment by waya279** [comment]
@naruse666 @R1013-T 
スプレッドシートに記入終わってます！
閉じちゃっていいですか？
