### ISSUE TITLE
ミドルウェアの実装

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#20]
- [x] [ログ](https://hono.dev/docs/middleware/builtin/logger#logger-middleware)
- [x] [CORS](https://hono.dev/docs/middleware/builtin/cors)（すべてのオリジンを許可）

**Comment by naruse666** [comment]
CORSは何で全て許可するんですか？
開発環境では全て許可でもいいですが、prodでは指定しないといけないと思ってます

**Comment by R1013-T** [comment]
@naruse666 
1. CORSですべて許可しないと、他の開発者がAPIにアクセスできなくないですか？
2. Cloudflareがやってくれるのか！そうしましょう！

**Comment by naruse666** [comment]
そうじゃん！APIのユーザーってフロントだけじゃないのか！
全て許可でいいと思います :+1:
