### ISSUE TITLE
snyk導入

### ISSUE THREAD

**Issue by waya279** [TECH-C-LT/Peace-Net#204]
Snyk：オープンソースの依存関係やコンテナ、インフラストラクチャコードのセキュリティ脆弱性を自動的に検出し、修正するためのツール

- [x] まずはメリット・デメリット調べる
- [x] 導入参考サイト探し
- [x] 導入
- [x] みんながアクセス出来るようにしたい！

**Comment by waya279** [comment]
◯Snykのメリット

1. セキュリティ脆弱性の検出:
Snykは、依存関係やコード内の脆弱性をスキャンし、既知のセキュリティ脅威を迅速に特定します。NPM、Maven、Pipなど、多くのパッケージマネージャーに対応しています。

2. 修正の提案と自動化:
脆弱性を検出した際に、Snykは修正方法を提案し、場合によっては自動的に修正を適用することができます。これにより、セキュリティリスクを迅速に解消できます。

3. GitHubなどのCI/CDツールとの統合:
SnykはGitHub、GitLab、Bitbucketなどのソースコード管理ツールやJenkinsなどのCI/CDツールとシームレスに統合でき、開発フローに組み込んで継続的なセキュリティチェックを行うことが可能です。

4. ライセンスコンプライアンス管理:
Snykは、オープンソースプロジェクトで使用されているライブラリのライセンスもチェックし、コンプライアンスに問題がないかを確認します。

5. 開発者フレンドリーなUI:
Snykのダッシュボードやレポート機能は、開発者にとって理解しやすいインターフェースで、問題の優先順位をつけやすくします。


◯Snykのデメリット
1. 無料版の制限:
Snykには無料版が存在しますが、スキャンできるプロジェクト数や脆弱性の深度には制限があります。大規模なチームやプロジェクトには、プレミアムプランが必要になる場合があります。

2. 誤検出の可能性:
一部の脆弱性スキャンでは、誤検出（false positives）が発生する可能性があります。これにより、開発者が不要な対応に追われることがあります。

3. 学習曲線:
特に初めて使用する場合、Snykのセットアップや結果の解釈にはある程度の学習が必要です。特に、ツールのカスタマイズやCI/CDパイプラインとの統合には技術的な理解が求められます。

4. インフラ依存:
Snykはクラウドベースのサービスであるため、使用する際にはインターネット接続が必要であり、オフライン環境やオンプレミス環境には適していません。

**Comment by naruse666** [comment]
snyk以外にも検証したいものあればやっていいですよ！

**Comment by R1013-T** [comment]
done
