### ISSUE TITLE
Sunshine APIの使用方法の記載

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#26]
- [x] 説明
- [x] 完全なURL構造
- [x] HTTPメソッド（GET, POST, PUT, DELETE など）
- [x] リクエストボディ
- [x] レスポンス形式とステータスコード
- [x] レスポンスの例
- [x] エラーレスポースの例と説明

**Comment by naruse666** [comment]
`apps/docs/src/components/HomepageFeatures/index.tsx`の coming soonの場所も変えて欲しい！
