### ISSUE TITLE
PrismAPIの実装 - API

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#291]

**Comment by waya279** [comment]
プロンプト
`受け取ったメッセージのポジティブな視点とネガティブな視点で捉えた時の候補を返すようにしてください。

「元気だね」
ポジティブ：元気があって良いね
ネガティブ：うるさい

こんな感じで例文を６つ出して返してください`



アンサー
`例文1:
元気だね
ポジティブ: 元気があって良いね
ネガティブ: うるさい

例文2:
頑張ってるね
ポジティブ: 努力家で素晴らしいね
ネガティブ: 無駄な努力

例文3:
面白いね
ポジティブ: ユーモアがあるね
ネガティブ: くだらない

例文4:
丁寧だね
ポジティブ: 配慮があって素晴らしい
ネガティブ: しつこい

例文5:
優しいね
ポジティブ: 思いやりがあって素敵だね
ネガティブ: 八方美人

例文6:
真面目だね
ポジティブ: 信頼できるね
ネガティブ: 堅苦しい`

**Comment by waya279** [comment]
プロンプト
`ネガティブな言葉の例文を６つお願いします`

---------------------------------------

アンサー
`1. **怠け者だね**  
ポジティブ: 自分のペースで取り組んでいる  
ネガティブ: やる気がない  

2. **つまらないね**  
ポジティブ: 落ち着いた雰囲気  
ネガティブ: 退屈  

3. **自信過剰だね**  
ポジティブ: 自己肯定感が高い  
ネガティブ: 傲慢  

4. **遅いね**  
ポジティブ: 丁寧に進めている  
ネガティブ: 進みが遅い  

5. **わがままだね**  
ポジティブ: 自分の意見をしっかり持っている  
ネガティブ: 他人の意見を聞かない  

6. **おせっかいだね**  
ポジティブ: 人を助けたい気持ちが強い  
ネガティブ: 余計な干渉`
