### ISSUE TITLE
資料作るぞ

### ISSUE THREAD

**Issue by naruse666** [TECH-C-LT/Peace-Net#293]
https://www.notion.so/ryu1013-share/9-29-110bef44a03c80db8960c3adf42483fe

### 事前準備TODO
- [x] 参考にできるスライドを探す @waya279 
- [x] 論文から説得力のある言葉を持ってくる @naruse666

**Comment by R1013-T** [comment]
https://docs.google.com/presentation/d/1l_ma5XuUpMBSLV9x84_l4cSM9tyv5h4t1TaD9_IcWk0/edit?hl=ja#slide=id.p

**Comment by naruse666** [comment]
論文から使えそうな文言
課題: 
原因:
解決策:

**Comment by waya279** [comment]
### 1. **課題 (Issue / Challenge)**

- **定義**: 取り組むべき問題や解決すべきテーマ・障害です。プロジェクトや日常の活動において、達成したい目標を妨げる要素が「課題」となります。
- **例**: 「リモートリポジトリをクローンしようとしたが、アクセスが拒否されている。」
- **特徴**: 課題は、まだ詳細な分析や調査を行っていない段階での、表面的な問題や目標です。

### 2. **原因 (Cause)**

- **定義**: 課題が発生した理由や要因です。問題がなぜ起こっているのかを突き止め、根本的な理由を明らかにします。原因を特定しないと、正確な解決策を導くことが困難です。
- **例**: 「アクセス権が不足しているため、フォルダやリポジトリの作成ができない。」
- **特徴**: 原因は、課題の詳細な分析の結果判明するもので、直接的・間接的な要素が含まれます。

### 3. **解決策 (Solution)**

- **定義**: 課題を解決し、原因に対処するための具体的なアクションや手段です。原因をもとに、適切な行動を取ることで課題を解消し、望む結果に向かって前進できます。
- **例**: 「管理者権限でコマンドを実行する、またはアクセス権限のあるディレクトリでクローンする。」
- **特徴**: 解決策は、原因に基づいて実行可能なアプローチであり、現実的かつ効果的である必要があります。

---

### 違いのまとめ

- **課題**は「解決しなければならない問題や目標」を指し、具体的な原因や対策がまだ明確になっていない状態。
- **原因**は「課題が発生した理由や背景」を示し、なぜその課題が起こっているのかを説明します。
- **解決策**は「原因を元に、課題を克服するための行動や手段」で、具体的にどのように対処すればよいかを示します。

---

## 課題

誹謗中傷が多すぎる＝誹謗中傷が簡単にできてしまう

## 原因

誹謗中傷になってしまう言葉を知らない（伝え方が間違っている）
相手がどう受け取るかを理解していない、わからない
誹謗中傷となる言葉だと知らない人もいるのでは？
→（したくてしている人とそうでない人（誹謗中傷をしてしまった形になってしまった人））
意見や考えの伝え方が間違っている人がいるのでは？

## 解決策

誹謗中傷が出来てしまう環境を変える（Guardian）
誹謗中傷となる言葉を知る（Guardian、Prism）
相手がどう受け取るか理解する（Prism）

**Comment by naruse666** [comment]
誹謗中傷が多すぎる＝誹謗中傷が簡単にできてしまう
SNSの匿名性によって誹謗中傷を発信しやすくなっている

シンプルに「多過ぎる！」。

**Comment by waya279** [comment]
誹謗中傷が簡単にできてしまう（環境）
なぜ？
投稿を防ぐor確認することがない
つまり？
投稿の自由度が高い
それに？
論文の「SNSの匿名性によって誹謗中傷を発信しやすくなっている」が後押しとなっている
