### ISSUE TITLE
インデックスの作成

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#32]

**Comment by naruse666** [comment]
インデックスってなんだっけ？なんのためにつけるんだっけ？

高カーディナリティ(カラムの取りうる値が多い)ものにつけるべしという記憶。
ORM? DB engine? によってはPKに勝手につけてくれるとかあるので一旦実際のテーブルを見てみたい。

**Comment by R1013-T** [comment]
よく知らないので調べながらやろうかなって程度なのですが、
自分も必須では無いと思っています。なので日程等は設定していません。
ただ、APIの使用ログを保存するので、そこはデータ多くなりそうだなって思っています。時間あれば調べてやってみようかなって感じです。

**Comment by naruse666** [comment]
テーブル定義見るとAPIの利用ごとにレコードが増えるのではなく、api_keyが使われた回数をカウントアップしていくだけなのであまりデータ量は増えない気がしてきました。

**Comment by R1013-T** [comment]
1日ごとエンドポイントごとに集計する感じです
確かにそんな多くはならないかもですね
