### ISSUE TITLE
Guardian APIのプロンプト調整

### ISSUE THREAD

**Issue by R1013-T** [TECH-C-LT/Peace-Net#47]

**Comment by naruse666** [comment]
## 調整すること
テストケースを用意して誹謗中傷かそうでないかをフラグによってテストしたい。

数値の調整をどうするかは悩みどころ

できれば自動化したい

**Comment by naruse666** [comment]
https://ja.wikipedia.org/wiki/%E8%AA%B9%E8%AC%97%E4%B8%AD%E5%82%B7
やる気が出たらこれを読みたい

**Comment by naruse666** [comment]
## 誹謗中傷のケース
## 批判のケース

**Comment by naruse666** [comment]
これについても改善の余地がないか議論したい。
```
0.0-0.2: ほぼ問題なし
0.3-0.5: 軽度の懸念あり
0.6-0.8: 中程度の問題あり
0.9-1.0: 深刻な問題あり
```

**Comment by naruse666** [comment]
「英語で考えて、日本語で回答してください」をプロンプトに含めてみて違いを観察する

**Comment by naruse666** [comment]
批判もブロックしたい場合は？

**Comment by naruse666** [comment]
プロンプトを試してみて、discriminationの項目の不必要を判断する。

**Comment by naruse666** [comment]
誹謗中傷かどうかを判断するフィールドなかった。これがないと批判かどうかの判断もできなくなるので追加。

**Comment by naruse666** [comment]
ハラスメントが誹謗中傷にカバーされてるからいらないかも？

もしくは`ハラスメント`という項目が抽象的なので`パワハラ`のように具体的な項目にしないと難しい。
